---
- name: Deploy application
  ansible.builtin.include_tasks: deploy.yml
  ignore_errors: yes

- name: Check deployment status
  shell: "curl -f http://{{ ansible_host }}:{{ app_port }}/health || exit 1"
  register: health_check
  retries: 3
  delay: 10
  ignore_errors: yes

- name: Rollback deployment if health check fails
  when: health_check.rc != 0
  ansible.builtin.include_tasks: rollback.yml
