---
- name: Install CloudWatch Agent
  hosts: all
  become: yes
  tasks:
    - name: Download CloudWatch Agent
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: /tmp/amazon-cloudwatch-agent.deb

    - name: Install CloudWatch Agent
      apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
        state: present

    - name: Create CloudWatch config directory
      file:
        path: /opt/aws/amazon-cloudwatch-agent/etc
        state: directory
        mode: 0755

    - name: Copy CloudWatch config file
      template:
        src: templates/cloudwatch-config.json.j2
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        mode: 0644

    - name: Start and enable CloudWatch Agent
      systemd:
        name: amazon-cloudwatch-agent
        enabled: yes
        state: started
